### ISSUE TITLE
site theme

### ISSUE THREAD

**Issue by devinhalladay** [erikmaclennan/erikmaclennan.github.io#1]
Hey man, I know I never did get back to you about using my site as a template (got busy, lost track of emails, etc, you know how these things go sometimes). I'd prefer it if you didn't use my site as a template of any sort for yours; I worked very hard on my website and there's nothing else like it out there that I've seen, so I don't want that quality and uniqueness being brought down by other people using my designs.

I open-sourced my site years ago just to be transparent and so people would be able to see some interesting things I'm doing with Middleman (and when I first started my site, with Jekyll).

If you'd like advice on getting started on your site or want me to point you to some open source themes you *can* use, let me know and I'd be happy to do so.

Thanks! Devin

**Comment by devinhalladay** [comment]
I know this is largely my fault through not communicating with you so you're at no fault but I'd still like it if you went another route for your site. I'm happy to help you out if you need some guidance!

**Comment by erikmaclennan** [comment]
Hey Devin, good to hear from you. This is no fault of your own! I totally understand where you are coming from here, and I will be sure to create my website from other means. Your website design has a really unique, clean aesthetic that I was instantly drawn to. Would love your advice on these matters.

Thanks very much for making the site open-source, as I have been able to learn quite a bit of the basics of Middleman and embedded ruby. Really would like to grow my skills in this area, and this has been a great starting point.

Cheers, 
Erik

**Comment by devinhalladay** [comment]
Cool! Thanks for being so understanding. If you DM me on Twitter or something (or just shoot me an email if that's easier) we can chat a little more about good starting points sometime early this week. I'm guessing you want to get your site up and running now that it's the new year so I wanna help make that a little easier!

**Comment by erikmaclennan** [comment]
Great! will do.
